### PR TITLE
Events page

### PR DESCRIPTION
**Pull request by merad99**

### CODE REVIEW

**Review by iamamonte — CHANGES_REQUESTED** [review]
Thanks, a few items:

Can you utilize state for all of the filters?
Can you also utilize the DisplayEvent component to render events?
Can you add the "Create Event" button at the top?

**Comment by merad99** [comment]
On it

**Review by iamamonte — APPROVED** [review]
Can separate out the state options into a separate function or component at a later date.

Will need to encapsulate the css classes being used.

**Comment by iamamonte** [comment]
Will also need to double check state.

**Pull request merged**
